import React from 'react'
import styles from "../styles/Home.module.css"
import Image from "next/image";
import Navbar from '../components/navbar';
import Head from 'next/head';
import aboutimg from "../public/assets/AboutUs.svg"
import Link from 'next/link';

const About = () => {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Issue Hunter | About Us</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Navbar />


                <main className={styles.main}>
                    <Image
                        alt="Next.js logo"
                        src={aboutimg}
                        width={1200}
                        height={400}
                    />
                    <h1 className={styles.title}>Here{"'"}s all about us !!</h1>

                    <p className={styles.description}>
                        Issue hunter is a place where the community solves your issue.
                        <br />
                        Be it a problem in your device, a  bug in your code, some github code changes or even personal problems, just post it in <Link href='/issues' className={styles.issuelink}>Issues</Link> and let the community help you !!
                    </p>
                </main>


            </div>
        </>
    )
}

export default About