import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import Navbar from "./navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
      <Head>
        <title>Issue Hunter | Tamal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>
      {/* //* This is the script tag it is used to integrate script tags and help us with stuffs like google adsense and so on */}
      {/* <Script strategy="lazyOnload" src="" ></Script> */}

      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Issue Hunter !!</h1>

        <p className={styles.description}>
          A place where the comunnity solves your issue !!
        </p>
      </main>
    </div>
  );
}
