import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Issue Hunter | Tamal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* //* This is the script tag it is used to integrate script tags and help us with stuffs like google adsense and so on */}
      {/* <Script strategy="lazyOnload" src="" ></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Issue Hunter !!</h1>

        <p className={styles.description}>
          A place where the comunnity solves your issue !!
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
